---
- name: Archive to Root Folder NGINX Default Files
  community.general.archive:
    path: /usr/share/nginx/html
    dest: /root/nginx-default.tgz
    mode: '0644'
- name: Remove NGINX Default Files
  ansible.builtin.command: "/usr/bin/rm -rf /usr/share/nginx/html/*"
- name: Update NGINX Server Config
  ansible.builtin.copy:
    src: files/nginx-http.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
- name: Copy Updated PHP Config Files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/php.d/
    owner: root
    group: root
    mode: '0644'
  with_items:
    - files/custom.ini
    - files/uploads.ini
- name: Copy new default start page 
  ansible.builtin.copy:
    src: files/index.php
    dest: /usr/share/nginx/html/index.php
    owner: root
    group: root
    mode: '0644'
- name: Set NGINX Server Startup Configuration
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
  when: enable_service
