---
- name: Add the Local NGINX Repository
  ansible.builtin.yum_repository:
    name: nginx
    description: NGINX Repository Mirror
    baseurl: "{{ repo_server }}/{{ repo_path }}"
    gpgcheck: true
    gpgkey: "{{ repo_server }}/{{ cert_path }}"
    enabled: true
    state: present
  when: not connected_network
- name: Add the Internet NGINX Repository
  ansible.builtin.yum_repository:
    name: nginx
    description: nginx stable Repository
    baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: true
    enabled: true
    gpgkey: https://nginx.org/keys/nginx_signing.key
  when: connected_network
- name: Enable Code-Ready Builder for RHEL 8
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
- name: Install EPEL 8 Release
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  when: connected_network
- name: Download and install latest Remi GPG Key
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2023
    state: present
  when: connected_network
- name: Install Remi Repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
  when: connected_network
- name: Install the NGINX and PHP 8.1 packages
  ansible.builtin.dnf:
    name:
      - nginx
      - php81-php-common
      - php81-php-fpm
      - php81-php-mysqlnd
      - php81-php-pecl-imagick
      - php81-php-pecl-zip
    state: present
