---
- name: Add the Local NGINX Repository
  ansible.builtin.yum_repository:
    name: nginx
    description: NGINX Repository Mirror
    baseurl: "{{ repo_server }}/{{ repo_path }}"
    gpgcheck: true
    gpgkey: "{{ repo_server }}/{{ cert_path }}"
    enabled: true
    state: present
  when: not connected_network
- name: Add the Internet NGINX Repository
  ansible.builtin.yum_repository:
    name: nginx
    description: nginx stable Repository
    baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: true
    enabled: true
    gpgkey: https://nginx.org/keys/nginx_signing.key
  when: connected_network
- name: Enable Code-Ready Builder for RHEL 8
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
- name: Install EPEL 8 GPG Key
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    fingerprint: 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
  when:
    - connected_network
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == '8'
- name: Install EPEL 9 GPG Key
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    fingerprint: FF8A D134 4597 106E CE81 3B91 8A38 72BF 3228 467C
  when:
    - connected_network
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == '9'
- name: Install EPEL 8 Release
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  when:
    - connected_network
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == '8'
- name: Install EPEL 9 Release
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present
  when:
    - connected_network
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == '9'
- name: Download and install latest Remi EL8 GPG Key
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
    state: present
  when:
    - connected_network
    - ansible_os_family == "RedHat" and ansible_distribution_major_version == '8'
- name: Install Remi Repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
  when: connected_network
- name: Install the NGINX and PHP 8.1 packages
  ansible.builtin.dnf:
    name:
      - nginx
      - php81-php-common
      - php81-php-fpm
      - php81-php-mysqlnd
      - php81-php-pecl-imagick
      - php81-php-pecl-zip
    state: present
